[package]
name = "advent_calendar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day_1 = { path = "../day_1" }
day_2 = { path = "../day_2" }
clap = { version = "4.0.29", features = ["derive"] }